### ISSUE TITLE
Small image of Newton at Top

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/newtonsMethodSurge#11]
Just an idea... a small image of newton at the top?  Good looking newton...
![image](https://cloud.githubusercontent.com/assets/4535729/17459854/6759326e-5c00-11e6-9611-3043055d6bf9.png)

not ugly newton though... small.
![image](https://cloud.githubusercontent.com/assets/4535729/17459857/7c77c1b0-5c00-11e6-88f0-e79f832746a8.png)

**Comment by rowens882** [comment]
Lol. Yes, pretty Newton would be best. Would it clutter the minimal design? What about fading in at the bottom?

**Comment by johnRedden** [comment]
Just an idea...  I was thinking a very small thumbnail in the title banner:

[pic] Newtons Method

If it does not look right nix the idea.

**Comment by rowens882** [comment]
Hmm, I see what you mean. That could be a good touch. Let me get a few people's opinions and see what they think about it. And Cory gets input too.
