### ISSUE TITLE
Only Integer Guesses?

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/newtonsMethodSurge#3]
Why only integer guesses?

Line 154:  `userGuess = parseInt(userGuess);`

Convert it to a float:  http://www.w3schools.com/jsref/jsref_parsefloat.asp

**Comment by johnRedden** [comment]
Round to 8 decimal places... here is the idea:   `parseFloat("123.456").toFixed(2);`

http://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-in-javascript

**Comment by rowens882** [comment]
Changed line from limiting to integers to 
userGuess = parseFloat(userGuess).toFixed(8);
