### ISSUE TITLE
One more iteration!

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/newtonsMethodSurge#9]
I honestly need one more iteration to show that the number is converging to 8 digits of accuracy.  As it sits I can only really see 2 digits:
![image](https://cloud.githubusercontent.com/assets/4535729/17459750/bd5bb566-5bfa-11e6-908f-097564ab1d81.png)

**Comment by rowens882** [comment]
I just updated with a fix. It adds one more iteration after the loop. See if it works for you.

**Comment by johnRedden** [comment]
3x^2 I can only see 4 places of accuracy... maybe we need more iterations?
![image](https://cloud.githubusercontent.com/assets/4535729/17459796/ae90a1b0-5bfd-11e6-999a-f446887902a1.png)

**Comment by johnRedden** [comment]
Acutally did you sync?

**Comment by rowens882** [comment]
I've synced just to be sure. See if that works, there's another fix I can try.

**Comment by johnRedden** [comment]
You are getting there... 3x^2-1  looks like seven places of accuracy:
![image](https://cloud.githubusercontent.com/assets/4535729/17459820/c903f83e-5bfe-11e6-96d2-ec3f06964f5e.png)

**Comment by rowens882** [comment]
Ok, I made the exit conditions on the do-while loop more precise.

**Comment by johnRedden** [comment]
Now that is what I want to see... the same number so no need to iterate further!  You should test other more complicated functions.
![image](https://cloud.githubusercontent.com/assets/4535729/17459835/96de2536-5bff-11e6-8319-63fceeb61e7b.png)
